### ISSUE TITLE
library "libjsc.so" not found

### ISSUE THREAD

**Issue by chinloongtan** [greentriangle/react-native-leveldb#4]
Hi author, thanks for this awesome library as an alternative to async storage. 

I encountered this issue after upgrading from `1.1.0` to `1.4.0` on android. Build was succeeded but app crashed after launching in Release mode.

```
05-31 18:41:31.804 30033 30160 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1672)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.reactnativeleveldb.LeveldbModule.<clinit>(LeveldbModule.java:11)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.reactnativeleveldb.LeveldbPackage.createNativeModules(LeveldbPackage.java:19)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
05-31 18:41:31.804 30033 30160 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)
```

I guess it has to do with this commit https://github.com/greentriangle/react-native-leveldb/commit/a2658307c2813ef8901e695a30c9c3697dd64d0e#diff-59c313fb0dfe322996885368a5a90d8f8400c2576bb64acc60467c2e79ecd2e9R42 (since version 1.3.0)

Any feedback on the issue is appreciated. 

```
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    enableHermes: true
```

**Comment by mrousavy** [comment]
You don't do any runtime specific stuff, do you? In that case it _should_ build fine even if you didn't mention anything about hermes in your buildfile. @chinloongtan can you make sure that this is actually the error? There might be some other error some lines above or below the one you sent.

**Comment by savv** [comment]
Hi @chinloongtan , did you find a solution to this issue, by any chance? I am now faced with the same issue, and would like to address fix it.
